[package]
name = "bevy_render"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"


[dependencies]
# bevy
bevy_app = { path = "../bevy_app" }
bevy_core = { path = "../bevy_core" }
bevy_transform = { path = "../bevy_transform" }
bevy_asset = { path = "../bevy_asset" }
bevy_derive = { path = "../bevy_derive" }
bevy_window = { path = "../bevy_window" }
legion = { path = "../bevy_legion" }

# rendering
spirv-reflect = "0.2.3"
glsl-to-spirv = { path = "../glsl-to-spirv" }
# TODO: move this to its own crate
png = "0.16.0"

# misc
log = { version = "0.4", features = ["release_max_level_info"] }
uuid = { version = "0.8", features = ["v4", "serde"] }
glam = { path =  "../bevy_glam" }
zerocopy = "0.3"
bitflags = "1.0"
smallvec = "1.4.0"
# TODO: replace once_cell with std equivalent if/when this lands: https://github.com/rust-lang/rfcs/pull/2788
once_cell = "1.3.1"
downcast-rs = "1.1.1"
thiserror = "1.0"