[package]
name = "bevy_pathfinder"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_asset = { path = "../bevy_asset" }
bevy_render = { path = "../bevy_render" }
legion = { path = "../bevy_legion" }

pathfinder_geometry = { path = "../pathfinder/geometry", features = ["shader_alignment_32_bits"] }
pathfinder_gpu = { path = "../pathfinder/gpu", features = ["shader_alignment_32_bits"] }
pathfinder_renderer = { path = "../pathfinder/renderer" }
pathfinder_simd = { path = "../pathfinder/simd" }
pathfinder_resources = { path = "../pathfinder/resources" }
pathfinder_color = { path = "../pathfinder/color" }
pathfinder_canvas = { path = "../pathfinder/canvas" }

zerocopy = "0.3.0"
byteorder = "1.3"
