[package]
name = "bevy_property"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
erased-serde = "0.3"
bevy_property_derive = { path = "bevy_property_derive" }
ron = { path = "../ron" }
glam = { path = "../bevy_glam" }
legion = { path = "../bevy_legion" }
smallvec = { version = "1.4", features = ["serde"] }