[package]
name = "bevy"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
legion = { git = "https://github.com/TomGillen/legion.git", rev = "940ef3bfcb77e5d074ee3184b776ff1600da228d" }
legion_transform = { path = "src/transform" }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "44fa1bc2fa208fa92f80944253e0da56cb7ac1fe"}
glam = "0.8.4"
winit = "0.20.0-alpha4"
glsl-to-spirv = "0.1"
zerocopy = "0.2"
log = "0.4"
env_logger = "0.7"
rand = "0.7.2"
gltf = "0.14.0"

[profile.release]
debug = true