[package]
name = "bevy"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[features]
default = ["headless", "wgpu", "winit"]
headless = ["asset", "core", "derive", "diagnostic", "input", "render", "serialization", "transform", "ui", "window"]
asset = ["bevy_asset"]
core = ["bevy_core"]
derive = ["bevy_derive"]
diagnostic = ["bevy_diagnostic"]
input = ["bevy_input"]
render = ["bevy_render"]
serialization = ["bevy_serialization"]
transform = ["bevy_transform"]
ui = ["bevy_ui"]
window = ["bevy_window"]
wgpu = ["bevy_wgpu"]
winit = ["bevy_winit"]

[dependencies]
# bevy
bevy_app = { path = "bevy_app" }
bevy_asset = { path = "bevy_asset", optional = true }
bevy_core = { path = "bevy_core", optional = true }
bevy_derive = { path = "bevy_derive", optional = true }
bevy_diagnostic = { path = "bevy_diagnostic", optional = true }
bevy_input = { path = "bevy_input", optional = true }
bevy_render = { path = "bevy_render", optional = true }
bevy_serialization = { path = "bevy_serialization", optional = true }
bevy_transform = { path = "bevy_transform", optional = true }
bevy_ui = { path = "bevy_ui", optional = true }
bevy_window = { path = "bevy_window", optional = true }
bevy_wgpu = { path = "bevy_wgpu", optional = true }
bevy_winit = { path = "bevy_winit", optional = true }
legion = { path = "bevy_legion" }

# other
log = { version = "0.4", features = ["release_max_level_info"] }
glam = "0.8.6"

[dev-dependencies]
rand = "0.7.2"
serde = { version = "1", features = ["derive"]}
serde_json = "1.0"
type-uuid = "0.1"
env_logger = "0.7"

[profile.dev]
opt-level = 3