[package]
name = "bevy"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[features]
default = ["wgpu", "winit"]

[dependencies]
legion = { path = "bevy_legion", features = ["serialize"] }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "a7b0d5ae5bc0934439ef559ed145e93f0117c39a", optional = true }
bitflags = "1.0"
glam = "0.8.6"
winit = { version = "0.22.0", optional = true }
zerocopy = "0.3"
log = { version = "0.4", features = ["release_max_level_info"] }
env_logger = "0.7"
rand = "0.7.2"
gltf = "0.14.0"
serde = { version = "1", features = ["derive"]}
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4", "serde"] }
erased-serde = "0.3"
type-uuid = "0.1"
shaderc = "0.6"
libloading = "0.5.2"
png = "0.16.0"
spirv-reflect = "0.2.3"
bevy_derive = { path = "bevy_derive" }
bevy_transform = { path = "bevy_transform" }
# TODO: replace once_cell with std equivalent if/when this lands: https://github.com/rust-lang/rfcs/pull/2788
once_cell = "1.3.1"

[profile.release]
debug = true
incremental = true

[profile.dev]
opt-level = 3