[package]
name = "bevy"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[features]
default = ["bevy_wgpu", "bevy_winit"]

[dependencies]
# bevy
bevy_app = { path = "bevy_app" }
bevy_asset = { path = "bevy_asset" }
bevy_core = { path = "bevy_core" }
bevy_derive = { path = "bevy_derive" }
bevy_diagnostic = { path = "bevy_diagnostic" }
bevy_input = { path = "bevy_input" }
bevy_render = { path = "bevy_render" }
bevy_transform = { path = "bevy_transform" }
bevy_ui = { path = "bevy_ui" }
bevy_window = { path = "bevy_window" }
bevy_wgpu = { path = "bevy_wgpu", optional = true }
bevy_winit = { path = "bevy_winit", optional = true }
legion = { path = "bevy_legion", features = ["serialize"] }

# logging
log = { version = "0.4", features = ["release_max_level_info"] }

# misc
glam = "0.8.6"
serde = { version = "1", features = ["derive"]}
erased-serde = "0.3"
type-uuid = "0.1"
# TODO: replace once_cell with std equivalent if/when this lands: https://github.com/rust-lang/rfcs/pull/2788
once_cell = "1.3.1"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
rand = "0.7.2"
serde_json = "1.0"
env_logger = "0.7"

[profile.dev]
opt-level = 3