[package]
name = "bevy_pbr"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_app = { path = "../bevy_app", version = "0.1.0" }
bevy_asset = { path = "../bevy_asset", version = "0.1.0" }
bevy_core = { path = "../bevy_core", version = "0.1.0" }
bevy_derive = { path = "../bevy_derive", version = "0.1.0" }
bevy_render = { path = "../bevy_render", version = "0.1.0" }
bevy_transform = { path = "../bevy_transform" }
bevy_window = { path = "../bevy_window", version = "0.1.0" }
legion = { path = "../bevy_legion"}

zerocopy = "0.3"
glam = { path =  "../bevy_glam" }