[package]
name = "bevy_asset"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_core = { path = "../bevy_core" }

uuid = { version = "0.8", features = ["v4", "serde"] }