[package]
name = "bevy_asset"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_core = { path = "../bevy_core" }
legion = { path = "../bevy_legion" }

uuid = { version = "0.8", features = ["v4", "serde"] }
crossbeam-channel = "0.4.2"
anyhow = "1.0"
thiserror = "1.0"