[package]
name = "example_plugin"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy = { path = "../../../../bevy" }
bevy_derive = { path = "../../../bevy_derive" }

[profile.release]
debug = true